export { exerciseTimeAt, formatExerciseTime, type ClockAnchor } from './clock';
export {
  isFiniteVec2,
  normalizeRotation,
  polygonArea,
  polygonCentroid,
  translatePoints,
  type Vec2,
} from './geometry';
export {
  initialState,
  visibilities,
  hydrantTypes,
  type Building,
  type BuildingId,
  type HydrantType,
  type MapFeature,
  type MapFeatureChanges,
  type MapFeatureId,
  type ClockState,
  type GameState,
  type SituationObject,
  type SituationObjectId,
  type Unit,
  type UnitId,
  type Visibility,
} from './state';
export type {
  Command,
  PlaceUnit,
  MoveUnit,
  RotateUnit,
  RemoveUnit,
  PlaceSituationObject,
  MoveSituationObject,
  RotateSituationObject,
  ResizeSituationObject,
  ChangeSituationObjectLength,
  ChangeSituationObjectVisibility,
  RemoveSituationObject,
  AddBuilding,
  MoveBuilding,
  ChangeBuilding,
  RemoveBuilding,
  AddMapFeature,
  MoveMapFeature,
  ChangeMapFeature,
  RemoveMapFeature,
  PauseClock,
  ResumeClock,
  SetClockSpeed,
} from './commands';
export type {
  GameEvent,
  UnitPlaced,
  UnitMoved,
  UnitRotated,
  UnitRemoved,
  SituationObjectPlaced,
  SituationObjectMoved,
  SituationObjectRotated,
  SituationObjectResized,
  SituationObjectLengthChanged,
  SituationObjectVisibilityChanged,
  SituationObjectRemoved,
  BuildingAdded,
  BuildingMoved,
  BuildingChanged,
  BuildingRemoved,
  MapFeatureAdded,
  MapFeatureMoved,
  MapFeatureChanged,
  MapFeatureRemoved,
  ClockPaused,
  ClockResumed,
  ClockSpeedChanged,
} from './events';
export { decide, type DecideResult, type Rejection } from './decide';
export { applyEvent, replay } from './apply';
export { Game } from './game';
export { presentationState } from './visibility';
export { pathLength } from './mapFeatures';
export {
  EXERCISE_FILE_FORMAT,
  EXERCISE_FILE_VERSION,
  parseExercise,
  serializeExercise,
  type ExerciseFile,
  type ExerciseFileError,
  type ParseExerciseResult,
} from './exerciseFile';
